package com.atlassian.jira.plugins.dvcs.querydsl.v3;

import com.atlassian.pocketknife.api.querydsl.SchemaProvider;
import com.mysema.query.sql.ColumnMetadata;
import com.mysema.query.sql.RelationalPathBase;
import com.mysema.query.types.path.NumberPath;
import com.mysema.query.types.path.StringPath;

import java.sql.Types;

import static com.mysema.query.types.PathMetadataFactory.forVariable;

/**
 * Generated by https://bitbucket.org/atlassian/querydsl-ao-code-gen
 */
public class QGitHubEventMapping extends RelationalPathBase<QGitHubEventMapping>
{

    private static final long serialVersionUID = -599669795L;

    public static final String AO_TABLE_NAME = "AO_E8B6CC_GIT_HUB_EVENT";

    public static final QGitHubEventMapping withSchema(SchemaProvider schemaProvider)
    {
        String schema = schemaProvider.getSchema(AO_TABLE_NAME);
        return new QGitHubEventMapping("GIT_HUB_EVENT", schema, AO_TABLE_NAME);
    }

    /**
     * Database Columns
     */
    // We have not yet built QueryDSL type support for java.util.Date getCreatedAt()


    public final StringPath GIT_HUB_ID = createString("GIT_HUB_ID");

    public final NumberPath<Integer> ID = createNumber("ID", Integer.class);

    // We have not yet built QueryDSL type support for com.atlassian.jira.plugins.dvcs.activeobjects.v3.RepositoryMapping getRepository()


    public final com.mysema.query.sql.PrimaryKey<QGitHubEventMapping> GIT_HUB_EVENT_PK = createPrimaryKey(ID);

    public QGitHubEventMapping(String variable, String schema, String table)
    {
        super(QGitHubEventMapping.class, forVariable(variable), schema, table);
        addMetadata();
    }

    private void addMetadata()
    {
        /**
         * Database Metadata is not yet used by QueryDSL but it might one day.
         */

        addMetadata(GIT_HUB_ID, ColumnMetadata.named("GIT_HUB_ID").ofType(Types.VARCHAR)); // .withSize(0).withNotNull()); // until detect primitive types, int ..
        addMetadata(ID, ColumnMetadata.named("ID").ofType(Types.INTEGER)); // .withSize(0).withNotNull()); // until detect primitive types, int ..

    }
}