package com.atlassian.jira.plugins.dvcs.querydsl.v3;

import com.atlassian.pocketknife.api.querydsl.SchemaProvider;
import com.mysema.query.sql.ColumnMetadata;
import com.mysema.query.sql.RelationalPathBase;
import com.mysema.query.types.path.NumberPath;
import com.mysema.query.types.path.StringPath;

import java.sql.Types;

import static com.mysema.query.types.PathMetadataFactory.forVariable;

/**
 * Generated by https://bitbucket.org/atlassian/querydsl-ao-code-gen
 */
public class QMessageMapping extends RelationalPathBase<QMessageMapping>
{

    private static final long serialVersionUID = 2136148333L;

    public static final String AO_TABLE_NAME = "AO_E8B6CC_MESSAGE";

    public static final QMessageMapping withSchema(SchemaProvider schemaProvider)
    {
        String schema = schemaProvider.getSchema(AO_TABLE_NAME);
        return new QMessageMapping("MESSAGE", schema, AO_TABLE_NAME);
    }

    /**
     * Database Columns
     */
    public final StringPath ADDRESS = createString("ADDRESS");

    public final NumberPath<Integer> ID = createNumber("ID", Integer.class);

    public final StringPath PAYLOAD = createString("PAYLOAD");

    public final StringPath PAYLOAD_TYPE = createString("PAYLOAD_TYPE");

    public final NumberPath<Integer> PRIORITY = createNumber("PRIORITY", Integer.class);

    // We have not yet built QueryDSL type support for com.atlassian.jira.plugins.dvcs.activeobjects.v3.MessageQueueItemMapping[] getQueuesItems()


    // We have not yet built QueryDSL type support for com.atlassian.jira.plugins.dvcs.activeobjects.v3.MessageTagMapping[] getTags()


    public final com.mysema.query.sql.PrimaryKey<QMessageMapping> MESSAGE_PK = createPrimaryKey(ID);

    public QMessageMapping(String variable, String schema, String table)
    {
        super(QMessageMapping.class, forVariable(variable), schema, table);
        addMetadata();
    }

    private void addMetadata()
    {
        /**
         * Database Metadata is not yet used by QueryDSL but it might one day.
         */
        addMetadata(ADDRESS, ColumnMetadata.named("ADDRESS").ofType(Types.VARCHAR)); // .withSize(0).withNotNull()); // until detect primitive types, int ..
        addMetadata(ID, ColumnMetadata.named("ID").ofType(Types.INTEGER)); // .withSize(0).withNotNull()); // until detect primitive types, int ..
        addMetadata(PAYLOAD, ColumnMetadata.named("PAYLOAD").ofType(Types.VARCHAR)); // .withSize(2147483647).withNotNull()); // until detect primitive types, int ..
        addMetadata(PAYLOAD_TYPE, ColumnMetadata.named("PAYLOAD_TYPE").ofType(Types.VARCHAR)); // .withSize(0).withNotNull()); // until detect primitive types, int ..
        addMetadata(PRIORITY, ColumnMetadata.named("PRIORITY").ofType(Types.INTEGER)); // .withSize(0).withNotNull()); // until detect primitive types, int ..


    }
}