package com.atlassian.jira.plugins.dvcs.querydsl.v3;

import com.atlassian.pocketknife.api.querydsl.SchemaProvider;
import com.mysema.query.sql.ColumnMetadata;
import com.mysema.query.sql.RelationalPathBase;
import com.mysema.query.types.path.NumberPath;
import com.mysema.query.types.path.StringPath;

import java.sql.Types;

import static com.mysema.query.types.PathMetadataFactory.forVariable;

/**
 * Generated by https://bitbucket.org/atlassian/querydsl-ao-code-gen
 */
public class QMessageTagMapping extends RelationalPathBase<QMessageTagMapping>
{

    private static final long serialVersionUID = -1641126187L;

    public static final String AO_TABLE_NAME = "AO_E8B6CC_MESSAGE_TAG";

    public static final QMessageTagMapping withSchema(SchemaProvider schemaProvider)
    {
        String schema = schemaProvider.getSchema(AO_TABLE_NAME);
        return new QMessageTagMapping("MESSAGE_TAG", schema, AO_TABLE_NAME);
    }

    /**
     * Database Columns
     */
    public final NumberPath<Integer> ID = createNumber("ID", Integer.class);

    // We have not yet built QueryDSL type support for com.atlassian.jira.plugins.dvcs.activeobjects.v3.MessageMapping getMessage()


    public final StringPath TAG = createString("TAG");


    public final com.mysema.query.sql.PrimaryKey<QMessageTagMapping> MESSAGE_TAG_PK = createPrimaryKey(ID);

    public QMessageTagMapping(String variable, String schema, String table)
    {
        super(QMessageTagMapping.class, forVariable(variable), schema, table);
        addMetadata();
    }

    private void addMetadata()
    {
        /**
         * Database Metadata is not yet used by QueryDSL but it might one day.
         */
        addMetadata(ID, ColumnMetadata.named("ID").ofType(Types.INTEGER)); // .withSize(0).withNotNull()); // until detect primitive types, int ..

        addMetadata(TAG, ColumnMetadata.named("TAG").ofType(Types.VARCHAR)); // .withSize(0)); // until detect primitive types, int ..
    }
}