package com.atlassian.jira.plugins.dvcs.querydsl.v3;

import com.atlassian.pocketknife.api.querydsl.SchemaProvider;
import com.mysema.query.sql.ColumnMetadata;
import com.mysema.query.sql.RelationalPathBase;
import com.mysema.query.types.path.NumberPath;
import com.mysema.query.types.path.StringPath;

import java.sql.Types;

import static com.mysema.query.types.PathMetadataFactory.forVariable;

/**
 * Generated by https://bitbucket.org/atlassian/querydsl-ao-code-gen
 */
public class QMessageConsumerMapping extends RelationalPathBase<QMessageConsumerMapping>
{

    private static final long serialVersionUID = -867447401L;

    public static final String AO_TABLE_NAME = "AO_E8B6CC_MESSAGE_CONSUMER";

    public static final QMessageConsumerMapping withSchema(SchemaProvider schemaProvider)
    {
        String schema = schemaProvider.getSchema(AO_TABLE_NAME);
        return new QMessageConsumerMapping("MESSAGE_CONSUMER", schema, AO_TABLE_NAME);
    }

    /**
     * Database Columns
     */
    public final StringPath CONSUMER = createString("CONSUMER");

    public final NumberPath<Integer> ID = createNumber("ID", Integer.class);

    // We have not yet built QueryDSL type support for java.util.Date getLastFailed()


    // We have not yet built QueryDSL type support for com.atlassian.jira.plugins.dvcs.activeobjects.v3.MessageMapping getMessage()


    public final NumberPath<Integer> RETRIES_COUNT = createNumber("RETRIES_COUNT", Integer.class);


    public final com.mysema.query.sql.PrimaryKey<QMessageConsumerMapping> MESSAGE_CONSUMER_PK = createPrimaryKey(ID);

    public QMessageConsumerMapping(String variable, String schema, String table)
    {
        super(QMessageConsumerMapping.class, forVariable(variable), schema, table);
        addMetadata();
    }

    private void addMetadata()
    {
        /**
         * Database Metadata is not yet used by QueryDSL but it might one day.
         */
        addMetadata(CONSUMER, ColumnMetadata.named("CONSUMER").ofType(Types.VARCHAR)); // .withSize(0)); // until detect primitive types, int ..
        addMetadata(ID, ColumnMetadata.named("ID").ofType(Types.INTEGER)); // .withSize(0).withNotNull()); // until detect primitive types, int ..


        addMetadata(RETRIES_COUNT, ColumnMetadata.named("RETRIES_COUNT").ofType(Types.INTEGER)); // .withSize(0)); // until detect primitive types, int ..
    }
}