package com.atlassian.jira.plugins.dvcs.querydsl.v3;

import com.atlassian.pocketknife.api.querydsl.SchemaProvider;
import com.mysema.query.sql.ColumnMetadata;
import com.mysema.query.sql.RelationalPathBase;
import com.mysema.query.types.path.NumberPath;
import com.mysema.query.types.path.StringPath;

import java.sql.Types;

import static com.mysema.query.types.PathMetadataFactory.forVariable;

/**
 * Generated by https://bitbucket.org/atlassian/querydsl-ao-code-gen
 */
public class QMessageQueueItemMapping extends RelationalPathBase<QMessageQueueItemMapping>
{

    private static final long serialVersionUID = 950691499L;

    public static final String AO_TABLE_NAME = "AO_E8B6CC_MESSAGE_QUEUE_ITEM";

    public static final QMessageQueueItemMapping withSchema(SchemaProvider schemaProvider)
    {
        String schema = schemaProvider.getSchema(AO_TABLE_NAME);
        return new QMessageQueueItemMapping("MESSAGE_QUEUE_ITEM", schema, AO_TABLE_NAME);
    }

    /**
     * Database Columns
     */
    public final NumberPath<Integer> ID = createNumber("ID", Integer.class);

    // We have not yet built QueryDSL type support for java.util.Date getLastFailed()


    // We have not yet built QueryDSL type support for com.atlassian.jira.plugins.dvcs.activeobjects.v3.MessageMapping getMessage()


    public final StringPath QUEUE = createString("QUEUE");

    public final NumberPath<Integer> RETRIES_COUNT = createNumber("RETRIES_COUNT", Integer.class);

    public final StringPath STATE = createString("STATE");

    public final StringPath STATE_INFO = createString("STATE_INFO");


    public final com.mysema.query.sql.PrimaryKey<QMessageQueueItemMapping> MESSAGE_QUEUE_ITEM_PK = createPrimaryKey(ID);

    public QMessageQueueItemMapping(String variable, String schema, String table)
    {
        super(QMessageQueueItemMapping.class, forVariable(variable), schema, table);
        addMetadata();
    }

    private void addMetadata()
    {
        /**
         * Database Metadata is not yet used by QueryDSL but it might one day.
         */
        addMetadata(ID, ColumnMetadata.named("ID").ofType(Types.INTEGER)); // .withSize(0).withNotNull()); // until detect primitive types, int ..


        addMetadata(QUEUE, ColumnMetadata.named("QUEUE").ofType(Types.VARCHAR)); // .withSize(0).withNotNull()); // until detect primitive types, int ..
        addMetadata(RETRIES_COUNT, ColumnMetadata.named("RETRIES_COUNT").ofType(Types.INTEGER)); // .withSize(0).withNotNull()); // until detect primitive types, int ..
        addMetadata(STATE, ColumnMetadata.named("STATE").ofType(Types.VARCHAR)); // .withSize(0).withNotNull()); // until detect primitive types, int ..
        addMetadata(STATE_INFO, ColumnMetadata.named("STATE_INFO").ofType(Types.VARCHAR)); // .withSize(0)); // until detect primitive types, int ..
    }
}